### ISSUE TITLE
A dependent dll was not found

### ISSUE THREAD

**Issue by cas1993per** [vnm-interactive/AirTouch#1]
When i try to build AirTouch it succeed but when i try to run it shows error saying "The code execution cannot proceed because ImiNect.dll was not found" Reinstalling the program may fix this problem and In the error list it shows The program '[128132] AirTouch-d.exe' has exited with code -1073741515 (0xc0000135) 'A dependent dll was not found'.

I tried to look for ImiNect.dll but i couldn't found it anywhere.

**Comment by vinjn** [comment]
Hi, try comment out this line and re-compile
https://github.com/jing-interactive/Cinder-DepthSensor/blob/master/include/DepthSensor.h#L17

**Comment by vinjn** [comment]
Fixed, please sync and build again.
